bot-token: ''
chat-channel-id: 1234
dc-output-format: '**#sender_mc_username#**: #mc_message#'
mc-output-format: '<#sender_dc_tag#> #dc_message#'
disable-mass-pings: true
disable-role-pings: true
disable-member-pings: true